// doctor-panel/src/components/ui/CustomAlert.tsx
import React from 'react';
import { IX, IAlert } from './icons';

interface Props {
  visible: boolean;
  title: string;
  message: string;
  onClose: () => void;
}

export default function CustomAlert({ visible, title, message, onClose }: Props) {
  if (!visible) return null;
  return (
    <div className="alert-overlay">
      <div className="alert-card">
        <div style={{ width: 64, height: 64, borderRadius: 18, background: 'var(--red-100)', color: 'var(--red-500)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 24 }}>
          <IAlert size={32} />
        </div>
        <h3 style={{ fontSize: 20, fontWeight: 700, color: 'var(--ink-900)', marginBottom: 10 }}>{title}</h3>
        <p style={{ fontSize: 14, color: 'var(--ink-500)', fontWeight: 500, lineHeight: 1.6, marginBottom: 32 }}>{message}</p>
        <button 
          onClick={onClose}
          className="btn btn-primary"
          style={{ width: '100%', height: 48 }}
        >
          Tamam
        </button>
      </div>
    </div>
  );
}

// doctor-panel/src/components/ui/CustomAlert.vue
<template>
  <div v-if="visible" class="alert-overlay">
    <div class="alert-card">
      <div style="width:64px;height:64px;border-radius:18px;background:var(--red-100);color:var(--red-500);display:flex;align-items:center;justify-content:center;margin-bottom:24px">
        <IAlert :size="32" />
      </div>
      <h3 style="font-size:20px;font-weight:700;color:var(--ink-900);margin-bottom:10px">{{ title }}</h3>
      <p style="font-size:14px;color:var(--ink-500);font-weight:500;line-height:1.6;margin-bottom:32px">{{ message }}</p>
      <button class="btn btn-primary" style="width:100%;height:48px" @click="$emit('close')">Tamam</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { IAlert } from './icons'
defineProps<{ visible: boolean; title: string; message: string }>()
defineEmits<{ close: [] }>()
</script>
